config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'sessions/new'
  root 'blogs#new'
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/blog.rb
class Blog < ApplicationRecord

  validates :content, presence: true
  validates :content, length: { in: 1..140 }
  validates :image, presence: true

  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:edit, :update, :destroy]

  def new
    # @blog = current_user.blogs.build
    @blog = Blog.new
  end

  def create

    @blog = current_user.blogs.build(blog_params)
    @user = @blog.user.name
    if @blog.save
      redirect_to new_blog_path, notice:"投稿を作成しました！"
      else
      render :"new"
    end

  end

  def index

    @blogs = Blog.all


  end

  def confirm
    # binding.irb
    # if logged_in?
    # @blog = Blog.new(blog_params)
    @blog = current_user.blogs.build(blog_params)
    # binding.irb
    render :new if @blog.invalid?
    # else
    # end
  end

  def show
  end

  def destroy

    @blog.destroy
    redirect_to blogs_path,notice:"投稿を削除しました！"

  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path,notice: "投稿を編集しました！"
    else
      render :edit
    end
  end



  private
  def blog_params
    params.require(:blog).permit(:title, :content,:image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
     session.delete(:user_id)
     flash[:notice] = 'ログアウトしました'
     redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
      @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog,local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="title">
    <%= form.label :内容 %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to "一覧表示", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>確認</h3>
<%= form_with(model: @blog,local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @blog.content %></p>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>
  <p>画像:<%= image_tag(@blog.image.url) if @blog.image && @blog.image.url%></p>
  <%= form.hidden_field :user %>
  <p>投稿者:<%= @blog.user.name %></p>
  <%= form.submit  "登録" %>
<% end %>

app/views/blogs/edit.html.erb
<h2>編集</h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>一覧</h1>
<table>
  <tr >
    <th>投稿者</th>
    <th>内容</th>
    <th>画像</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.user.name %></td>
    <td><%= blog.content %></td>
    <td><%= image_tag(blog.image.url) %></td>
    <td><%= link_to '編集', edit_blog_path(blog.id)%></td>
    <td><%= link_to '削除', blog_path(blog.id), method: :delete %></td>
  </tr>
<% end %>
</table><br>
<%= link_to '投稿', new_blog_path %>

app/views/blogs/new.html.erb
<h2>投稿</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image.url %>
</p>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id = "a">Facebook</P>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "新規投稿", new_blog_path(current_user.id) %>
      <%= link_to "投稿一覧", blogs_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<p>メールアドレス: <%= @user.email %></p>